#!/bin/bash
#PBS -q sequentiel
#PBS -l mem=60g
#PBS -l walltime=3:00:00 

cd $PBS_O_WORKDIR
source /usr/share/Modules/3.2.10/init/bash # to get the 'module' command
module load anaconda-py3.6/4.3.13

cd /appli/anaconda/3.7/bin
source activate croco  


cd $PBS_O_WORKDIR
echo "you use " $OMP_NUM_THREADS "threads for your omp jobs"
date

python make_video_3D.py 28 > output_job_inputs

echo 3D figure created
date

